In [122]:
import pandas as pd
import sqlalchemy as db

In [123]:
conn = pd.read_json('connection.json', typ='series')
host = conn['host']
user = conn['user']
password = conn['password']
port = conn['port']

db_name = input('DB Name: ')
engine = db.create_engine('mysql+pymysql://' + user + ':' + password + '@' + host + ':' + port + '/' + db_name)

DB Name: GAPA321C

In [124]:
data = pd.read_sql('SELECT * FROM `rp9921-2022`', engine)

In [125]:
data

,index,Frame-Sf,SfCount,Time,Status,UTC_HOUR,UTC_MIN,UTC_SEC,PHASE_1,LATP,...,AP_2,ATS_ENGAGED,MACH_SELECT,LDG_LH,LDG_NOSE,LDG_RH,ID,Date,Plane,RM
0,0,43-1,172,04:31:03,None,4.0,NaN,NaN,NaN,14.505388,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
1,1,43-2,173,04:31:04,None,NaN,NaN,NaN,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
2,2,43-3,174,04:31:05,None,NaN,NaN,NaN,2.0,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
3,3,43-4,175,04:31:06,None,NaN,31.0,6.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
4,4,44-1,176,04:31:07,None,4.0,NaN,NaN,NaN,14.505045,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034439,6563,1667-4,6671,12:03:54,None,NaN,3.0,54.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034440,6564,1668-1,6672,12:03:55,None,12.0,NaN,NaN,NaN,14.491655,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034441,6565,1668-2,6673,12:03:56,None,NaN,NaN,NaN,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034442,6566,1668-3,6674,12:03:57,None,NaN,NaN,NaN,9.0,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034443,6567,1668-4,6675,12:03:58,None,NaN,3.0,58.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921

In [133]:
df = pd.DataFrame()
offsetError = 0
i = 0
year = 2022

def query(hourNum, year, data):
    global offsetError
    global df
#     query = f"SELECT `index`, ID, Time, Date, FF_1, FF_2 FROM `{acft_model}-{year}` LIMIT 3600 OFFSET {hourNum * 3600 - offsetError};"
    new_df = data[hourNum * 3600 : hourNum * 3600 + 3600]
    if new_df['ID'].nunique() > 1:
        id_select = min(new_df['ID'].unique())
        f_df = new_df[new_df['ID'] == id_select]
        offsetError += len(new_df[new_df['ID'] == max(new_df['ID'].unique())])
        new_df = f_df
    print(new_df)
    ID = min(new_df['ID'].unique())
    ff1 = sum(new_df['FF_1']) / 3600
    ff2 = sum(new_df['FF_2']) / 3600
    Date = max(pd.to_datetime(new_df['Date']))
    year = Date.year
    month = Date.month
    date = Date.day
    min_hour = min(pd.to_datetime(new_df['Time']).dt.hour)
    max_hour = max(pd.to_datetime(new_df['Time']).dt.hour)
    length = len(new_df)
    min_time = new_df['Time'][0]
    max_time = new_df['Time'][length-1]
    if min_hour == 0 and max_hour == 23:
        max_hour = 0
    create_df = {'ID':ID, 'year':year, 'month':month, 'date':date, 'hour':max_hour, 'ff1':ff1, 'ff2':ff2, 'min_time': min_time, 'max_time': max_time, 'len':length}
    create_df = pd.DataFrame(create_df, index=[0])
    df = pd.concat([df, create_df])
    print(hourNum, ID, year, month, date, max_hour, min_time, max_time, length, offsetError)

print("hourNum, ID, year, month, date, max_hour, min_time, max_time, length, offsetError")
while i <= len(data) / 3600:
    query(i, year, data)
    i += 1

hourNum, ID, year, month, date, max_hour, min_time, max_time, length, offsetError
      index Frame-Sf  SfCount      Time Status  UTC_HOUR  UTC_MIN  UTC_SEC  \
0         0     43-1      172  04:31:03   None       4.0      NaN      NaN
1         1     43-2      173  04:31:04   None       NaN      NaN      NaN
2         2     43-3      174  04:31:05   None       NaN      NaN      NaN
3         3     43-4      175  04:31:06   None       NaN     31.0      6.0
4         4     44-1      176  04:31:07   None       4.0      NaN      NaN
...     ...      ...      ...       ...    ...       ...      ...      ...
3595   3595    941-4     3767  05:30:58   None       NaN     30.0     58.0
3596   3596    942-1     3768  05:30:59   None       5.0      NaN      NaN
3597   3597    942-2     3769  05:31:00   None       NaN      NaN      NaN
3598   3598    942-3     3770  05:31:01   None       NaN      NaN      NaN
3599   3599    942-4     3771  05:31:02   None       NaN     31.0      2.0

      PHASE_1       LATP  ...  AP_2  ATS_ENGAGED  MACH_SELECT          LDG_LH  \
0         NaN  14.505388  ...     N  NOT_ENGAGED        SPEED      COMPRESSED
1         NaN        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
2         2.0        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
3         NaN        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
4         NaN  14.505045  ...     N  NOT_ENGAGED        SPEED      COMPRESSED
...       ...        ...  ...   ...          ...          ...             ...
3595      NaN        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3596      NaN  10.868914  ...     N      ENGAGED        SPEED  NOT COMPRESSED
3597      NaN        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3598      6.0        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3599      NaN        NaN  ...     N      ENGAGED         None  NOT COMPRESSED

           LDG_NOSE          LDG_RH  ID        Date    Plane      RM
0        COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
1        COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
2        COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
3        COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
4        COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
...             ...             ...  ..         ...      ...     ...
3595  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3596  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3597  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3598  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3599  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921

[3600 rows x 53 columns]
0 3 2022 1 1 5 04:31:03 05:31:02 3600 0
      index Frame-Sf  SfCount      Time Status  UTC_HOUR  UTC_MIN  UTC_SEC  \
3600   3600    943-1     3772  05:31:03   None       5.0      NaN      NaN
3601   3601    943-2     3773  05:31:04   None       NaN      NaN      NaN
3602   3602    943-3     3774  05:31:05   None       NaN      NaN      NaN
3603   3603    943-4     3775  05:31:06   None       NaN     31.0      6.0
3604   3604    944-1     3776  05:31:07   None       5.0      NaN      NaN
...     ...      ...      ...       ...    ...       ...      ...      ...
4691   4691   1215-4     4863  05:49:14   None       NaN     49.0     14.0
4692   4692   1216-1     4864  05:49:15   None       5.0      NaN      NaN
4693   4693   1216-2     4865  05:49:16   None       NaN      NaN      NaN
4694   4694   1216-3     4866  05:49:17   None       NaN      NaN      NaN
4695   4695   1216-4     4867  05:49:18   None       NaN     49.0     18.0

      PHASE_1       LATP  ...  AP_2  ATS_ENGAGED  MACH_SELECT          LDG_LH  \
3600      NaN  10.864794  ...     N      ENGAGED        SPEED  NOT COMPRESSED
3601      NaN        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3602      6.0        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3603      NaN        NaN  ...     N      ENGAGED         None  NOT COMPRESSED
3604      NaN  10.861017  ...     N      ENGAGED        SPEED  NOT COMPRESSED
...       ...        ...  ...   ...          ...          ...             ...
4691      NaN        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
4692      NaN  10.764544  ...     N  NOT_ENGAGED        SPEED      COMPRESSED
4693      NaN        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
4694      9.0        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED
4695      NaN        NaN  ...     N  NOT_ENGAGED         None      COMPRESSED

           LDG_NOSE          LDG_RH  ID        Date    Plane      RM
3600  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3601  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3602  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3603  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
3604  NO COMPRESSED  NOT COMPRESSED   3  2022-01-01  GAP2131  RP9921
...             ...             ...  ..         ...      ...     ...
4691     COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
4692     COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
4693     COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
4694     COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921
4695     COMPRESSED      COMPRESSED   3  2022-01-01  GAP2131  RP9921

[1096 rows x 53 columns]

KeyError: 0

In [132]:
df

,ID,year,month,date,hour,ff1,ff2,min_time,max_time,len
0,3,2022,1,1,5,1260.793056,1296.037222,04:31:03,05:31:02,3600

,index,Frame-Sf,SfCount,Time,Status,UTC_HOUR,UTC_MIN,UTC_SEC,PHASE_1,LATP,...,AP_2,ATS_ENGAGED,MACH_SELECT,LDG_LH,LDG_NOSE,LDG_RH,ID,Date,Plane,RM
0,0,43-1,172,04:31:03,None,4.0,NaN,NaN,NaN,14.505388,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
1,1,43-2,173,04:31:04,None,NaN,NaN,NaN,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
2,2,43-3,174,04:31:05,None,NaN,NaN,NaN,2.0,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
3,3,43-4,175,04:31:06,None,NaN,31.0,6.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
4,4,44-1,176,04:31:07,None,4.0,NaN,NaN,NaN,14.505045,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,3,2022-01-01,GAP2131,RP9921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034439,6563,1667-4,6671,12:03:54,None,NaN,3.0,54.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034440,6564,1668-1,6672,12:03:55,None,12.0,NaN,NaN,NaN,14.491655,...,N,NOT_ENGAGED,SPEED,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034441,6565,1668-2,6673,12:03:56,None,NaN,NaN,NaN,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034442,6566,1668-3,6674,12:03:57,None,NaN,NaN,NaN,9.0,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921
3034443,6567,1668-4,6675,12:03:58,None,NaN,3.0,58.0,NaN,NaN,...,N,NOT_ENGAGED,None,COMPRESSED,COMPRESSED,COMPRESSED,5095,2022-12-31,GAP2526,RP9921